### ISSUE TITLE
Add python glue

### ISSUE THREAD

**Issue by olear** [olear/audiocurve#1]
Add the glue between cli and Natron.

**Comment by olear** [comment]
get pyplug path and use that to prefix audiocurve cmd

**Comment by olear** [comment]
Clean up params

**Comment by olear** [comment]
duration param should check for audio length and adapt (if possible)

**Comment by olear** [comment]
Also supported audio formats if possible in the filedialog

**Comment by rcspam** [comment]
Hi, I just got back home and 'git pull' audiocurve...
Good jobs. 
How can help you ?

**Comment by rcspam** [comment]
Do you speak about duration param  in python script or in audiocurve executable ?

**Comment by olear** [comment]
duration is now frames. Will do some minor changes to the python script, and get it working on Windows. Then a quick review and release (this weekend).

**Comment by olear** [comment]
I think we have enough features for v1, will do some minor cleanup and try to make an installer.
