### ISSUE TITLE
fps int to float

### ISSUE THREAD

**Issue by rcspam** [olear/audiocurve#7]
I suggest to change fps param type into float in 'AudioCurve' executable'. Project frameRate is doubleParam.
If we set frameRate in the Py script to take frameRate of the project as Default value.
Most video can be 29.97 fps...

**Comment by olear** [comment]
will do.

**Comment by rcspam** [comment]
I try to debug windows version on wine... 
Error at asciiAC: change 'from os import *' to ' from os import path'
Now the error is at "x, y = asciiAC.readline().split ("_")"...

**Comment by rcspam** [comment]
This last error happend in Linux and OSX too, but the animate curve is set, so i don't know why, perhaps try to recode readline file differently ! I must go so i ll try to fix this later !

**Comment by rcspam** [comment]
AudioCurve  must write both values in the ascii file (e.g.: 5.1351254576_0.00000 for x or 0.00000_5.1351254576 for y) as i do in audio2ascii.sh, then when pyplug readline() range it in a list: x, y = asciiAC.readline().split ("_").
If you try current AudioCurve.exe, it's ok when with 'xy' ...

**Comment by olear** [comment]
Ok, will do some test when I get home.

**Comment by olear** [comment]
outputting x+y always don't work.... breaks pyplug

**Comment by rcspam** [comment]
If i replace 'from os import *' by 'from os import path' in you AudioCurve.py. that's all.
It works fine.

https://dl.dropboxusercontent.com/u/2677320/screenshot-2015-07-19_00.03.44.mp4

**Comment by rcspam** [comment]
xy: not grave AudioCurve.py works without changing them

**Comment by rcspam** [comment]
Impossible to build MacOsx version with qtcreator ?

**Comment by olear** [comment]
building on Mac should be as easy as on Linux as long as Qt is installed.

**Comment by rcspam** [comment]
I want to say cross-compile from Linux or win64

**Comment by rcspam** [comment]
I have install a OSX on virtualBox but it was to debug mac version of audio2ascii,, it s very slow and it's so .... I'll uninstall it soon.

**Comment by olear** [comment]
I don't know anything about building on Mac :)

I built win32 (audiocurve/sox) bin using MXE (win64 is pointless) on CentOS7, and for Linux I built the bin against the Natron SDK on CentOS6.2.

**Comment by rcspam** [comment]
Impossible to cross-compil OSx bin ?

**Comment by olear** [comment]
don't know.

**Comment by rcspam** [comment]
Wit your win build we can base audioCurve.py on Audiotoascii.py and use audio2ascii for mac version

**Comment by rcspam** [comment]
Have you some ideas for ffplay bagrounded on win32 ?

**Comment by olear** [comment]
will look into sound later (v1+), my first focus is getting things stable.

**Comment by rcspam** [comment]
Sure! Good Night

**Comment by rcspam** [comment]
I forgot, I want to use your audiocurve build to distribute with audio2ascii, how do that from github (license etc)

**Comment by olear** [comment]
We will find out something :)

**Comment by rcspam** [comment]
I have only 1 Billion Dollards o my bank account, do you think it s sufficient ?

**Comment by olear** [comment]
That should be enough :)

Audiocurve can be included as an submodule, or I can do a pull request with what you need tomorrow. Audiocurve is licenced under the BSD licence, shouldn't be a problem.

**Comment by olear** [comment]
To save you some time etc, just use the exe's from https://github.com/olear/audiocurve/releases/download/1.0rc1/AudioCurve-1.0rc1-win32.linux64.zip works on win32/win64, sox has been built with all formats supported, the binaries are static and need no depends.

**Comment by olear** [comment]
add '-alwaysXY' if you need zeros.

**Comment by rcspam** [comment]
I just need an exec for win and linux to replace audio2ascii.sh which will stay here for OSX.
I'll take a look about cross-compile for qt OSX.

**Comment by rcspam** [comment]
If you have time can take a look at this https://github.com/tpoechtrager/osxcross

**Comment by olear** [comment]
Don't have access to workstation at the moment, so no big builds. Also I don't builds stuff I can't test :) There are enough Mac users around, one of them must me able to build something.

**Comment by rcspam** [comment]
You are right, nobody use windows ;))

**Comment by olear** [comment]
Win is no problem, but as I don't have access to Mac I can't test or build anything there, and I don't have the resources (or time) to test OSX in VBox or similar.

**Comment by rcspam** [comment]
No problem it was just a joke ! It's Sunday today with sun in the sky ! So i'm very happy !!!

**Comment by olear** [comment]
I know :)

**Comment by olear** [comment]
btw, I haven't built a Linux32 binary of AudioCurve yet. But on Linux it's easier to just built from source than downloading zip ;)

**Comment by rcspam** [comment]
I have try open your .pro file in QTCreator, i regret i suck at qt/c/c++, it really a cool app.
Good Sunday

**Comment by olear** [comment]
Qt is easy :)

sox.cpp/sox.h is the "library" and audiocurve.cpp is the cmdline wrapper. If you go back in history (in the repo) you will also find the gui stuff (that I removed).

**Comment by rcspam** [comment]
I have read and understand some stuff but i have really no time to really focus on it. But why not in the future, so....

**Comment by olear** [comment]
That's ok :)

just add a issue or something if you want something changed in AudioCurve.

**Comment by rcspam** [comment]
I have made lot of comment in AudioToAscii.py, so you'll not waist your time to add some param at AudioCurve.py. All works fine on Lin/mac/win. the only thing to do is " put apps (ffplay and 'audio editor') in background on win", i really don't love this system (sorry it's not a troll)

**Comment by rcspam** [comment]
This time i must go ! Good 'Sun' Day !

**Comment by olear** [comment]
will test ffplay etc on win, but I don't know if I can make it today, have some work to do.

Don't care for Win either, but I need it for some apps.

**Comment by rcspam** [comment]
No urgence, bye
