### ISSUE TITLE
Unable to generate curve data

### ISSUE THREAD

**Issue by rcspam** [olear/audiocurve#9]
I am just testing audicurve on 'windows 7'. Apparently it doesn't find sox.exe, if i am right : 'Unable to generate curve data'.

**Comment by olear** [comment]
sox.exe is in same folder?

Den 2015-07-23 17:43, skrev rcspam:

**Comment by rcspam** [comment]
yes installed with you setup

**Comment by olear** [comment]
"unable to generate curve data"  happens when sox gives no output/data, maybe wrong params (input/output)?

**Comment by rcspam** [comment]
just input a file in audiocurve plugin then generate curve so...

**Comment by rcspam** [comment]
I've try on another host, all is ok !
Don't know why i doesn't works on the other one.
Surely the secret ghosts of the compinting !?

**Comment by hafuz** [comment]
In Fact, **sox for win32** doesn't support mp3 files. It is not compiled, i hope to have well understood, with liblame....

**Comment by olear** [comment]
https://github.com/mxe/mxe/blob/master/src/sox.mk#L11

Should support mp3 (untested).

**Comment by hafuz** [comment]
Just an info for users who want use AudioCurve.exe...

**Comment by rcspam** [comment]
If you want sox read mp3 files, you have just to include [libmad.dll](http://ossbuild.googlecode.com/svn/trunk/Shared/Build/Windows/Win32/bin/libmad-0.dll) and [libmp3lame.dll](http://ossbuild.googlecode.com/svn/trunk/Shared/Build/Windows/Win32/bin/libmp3lame-0.dll) in sox.exe directory

**Comment by rcspam** [comment]
So, it is the same directory as Plugins !
